apiVersion: v1
kind: Service
metadata:
  name: openshift_carapp
spec:
  type: NodePort
  selector:
    app: openshift_carapp
  ports:
  - port: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift_carapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openshift_carapp
  template:
     metadata:
        labels:
           app: openshift_carapp
     spec:
       containers:
       - name: api
         image: rloman/openshift_carapp_api:latest	# Replace 'rloman' below 'api' section with your Docker hub id or prefix with the registry
         ports:
         - containerPort: 8080
